# Generated by Django 3.1.3 on 2020-12-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201212_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_category',
            field=models.ManyToManyField(blank=True, null=True, through='news.PostCategory', to='news.Category'),
        ),
    ]
